# Название воркфлоу, которое будет отображаться в GitHub
name: Check Hugging Face Key

# Триггер для запуска:
# workflow_dispatch позволяет запускать этот воркфлоу вручную
# со страницы "Actions" вашего репозитория.
on:
  workflow_dispatch:

jobs:
  # Название единственного задания в нашем воркфлоу
  check-key:
    # Указываем, что задание будет выполняться на последней версии Ubuntu
    # В этом окружении уже есть все необходимые инструменты для сборки
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование вашего репозитория
      # Это нужно, чтобы получить доступ к скрипту check_key.py
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python
      # Мы указываем версию 3.10, но можно использовать и другую
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: Установка зависимостей
      # Здесь выполняется та самая команда, которая не работала локально
      - name: Install dependencies
        run: pip install huggingface_hub

      # Шаг 4: Запуск скрипта для проверки ключа
      # Самое важное: мы безопасно передаем токен из секретов GitHub
      # в переменную окружения HF_TOKEN, которую читает наш Python-скрипт.
      - name: Run check script
        run: python check_key.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

